// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4AMDmnVXIOc0r9uoda1-LcNeGfIXo3ZY',
    appId: '1:559549378265:web:3d55ceb72bd030f2f718c8',
    messagingSenderId: '559549378265',
    projectId: 'nestify-cc1e3',
    authDomain: 'nestify-cc1e3.firebaseapp.com',
    storageBucket: 'nestify-cc1e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyHAEUcsS4pWX3Tc4nxIcfKDpaUpJKUlA',
    appId: '1:559549378265:android:fa43b223439dfa1df718c8',
    messagingSenderId: '559549378265',
    projectId: 'nestify-cc1e3',
    storageBucket: 'nestify-cc1e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRuWE3WeMy1uDryZxv4vP9ZjEzV9WmXCY',
    appId: '1:559549378265:ios:3e4f18d2f6dd4bd3f718c8',
    messagingSenderId: '559549378265',
    projectId: 'nestify-cc1e3',
    storageBucket: 'nestify-cc1e3.appspot.com',
    iosBundleId: 'com.example.nestify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRuWE3WeMy1uDryZxv4vP9ZjEzV9WmXCY',
    appId: '1:559549378265:ios:3e4f18d2f6dd4bd3f718c8',
    messagingSenderId: '559549378265',
    projectId: 'nestify-cc1e3',
    storageBucket: 'nestify-cc1e3.appspot.com',
    iosBundleId: 'com.example.nestify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4AMDmnVXIOc0r9uoda1-LcNeGfIXo3ZY',
    appId: '1:559549378265:web:9344836b0d5a06eaf718c8',
    messagingSenderId: '559549378265',
    projectId: 'nestify-cc1e3',
    authDomain: 'nestify-cc1e3.firebaseapp.com',
    storageBucket: 'nestify-cc1e3.appspot.com',
  );
}
